baseURL = "https://gomezarceo.mx/"
languageCode = "en-us"
title = "Gomez Arceo"
theme = "m10c"

[Author]
  name = "Alejandro Gomez"

# And you can even create generic menu
# [[menu.main]]
#   identifier = "about"
#   name       = "About"
#   url        = "/about"

# [[menu.main]]
#   identifier = "blog"
#   name       = "Blog"
#   url        = "/posts"

[params]
  avatar = "images/portrait.jpg"
  description = "I am a web engineer with a passion for creating software that impacts the lives of people."
  mainSections = ["about"]

  [[params.social]]
    icon = "twitter"
    name = "My Twitter"
    url = "https://twitter.com/alexserver"
  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/alexserver"
  [[params.social]]
    icon = "linkedin"
    name = "My LinkedIn"
    url = "https://linkedin.com/alejandrogomezarceo"
  [[params.social]]
    icon = "mail"
    name = "My Email"
    url = "mailto:alejandro@gomezarceo.mx"