baseURL = "https://gomezarceo.mx/"
languageCode = "en-us"
title = "Alejandro Gomez"
theme = "m10c"

[Author]
  name = "Alejandro Gomez"

# And you can even create generic menu
[[menu.main]]
  identifier = "en"
  name       = "English"
  url        = "/"

[[menu.main]]
  identifier = "es"
  name       = "Español"
  url        = "/es"
# [[menu.main]]
#   identifier = "blog"
#   name       = "Blog"
#   url        = "/posts"

[params]
  avatar = "images/portrait.jpg"
  description = "Passionate about always evolving and learning. I speak JS, and I love it, still, I can adapt and enjoy working with other stacks though. Adaptation ends suffering."
  mainSections = ["about"]

  [[params.social]]
    icon = "twitter"
    name = "My Twitter"
    url = "https://twitter.com/alexserver"
  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/alexserver"
  [[params.social]]
    icon = "linkedin"
    name = "My LinkedIn"
    url = "https://linkedin.com/alejandrogomezarceo"
  [[params.social]]
    icon = "mail"
    name = "My Email"
    url = "mailto:alejandro@gomezarceo.mx"